apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-db
  name: mydb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
      name: my-db
    spec:
      containers:
      - image: mysql
        name: my-db
