apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test1
  name: test2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test3
  template:
    metadata:
      labels:
        app: test3
      name: test4
    spec:
      containers:
      - image: nginx:alpine
        name: test5
